---

- name: assert | Test if types_strings is set correctly
  ansible.builtin.assert:
    that:
      - types_strings is defined
      - types_strings is iterable
    quiet: true

- name: assert | Test if types_integers is set correctly
  ansible.builtin.assert:
    that:
      - types_integers is defined
      - types_integers is iterable
    quiet: true

- name: assert | Test if types_booleans is set correctly
  ansible.builtin.assert:
    that:
      - types_booleans is defined
      - types_booleans is iterable
    quiet: true

- name: assert | Test if types_floats is set correctly
  ansible.builtin.assert:
    that:
      - types_floats is defined
      - types_floats is iterable
    quiet: true
